"""init freights with TripRequestStatus

Revision ID: a526cf623cc4
Revises: 5a0666d3392b
Create Date: 2025-09-22 01:47:38.553819

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a526cf623cc4'
down_revision: Union[str, Sequence[str], None] = '5a0666d3392b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('freights', 'status',
               existing_type=postgresql.ENUM('DRAFT', 'PENDING', 'MATCHED', 'MATCHING', 'CONFIRMED', 'IN_PROGRESS', 'COMPLETED', 'CANCELED', 'EXPIRED', 'SEARCHING', 'FAILED', 'ACCEPTED', 'TIMEOUT', 'REJECTED', name='triprequeststatus'),
               type_=sa.Enum('ACCEPTED', 'STARTING', 'DRAFT', 'PENDING', 'MATCHED', 'CONFIRMED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'EXPIRED', 'SEARCHING', 'FAILED', 'DRIVERS_FOUND', 'OFFERS_SENT', name='freightstatus'),
               existing_nullable=True)
    op.drop_constraint(op.f('freights_matching_id_fkey'), 'freights', type_='foreignkey')
    op.drop_column('freights', 'matching_id')
    op.add_column('matchings', sa.Column('freight_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'matchings', 'freights', ['freight_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'matchings', type_='foreignkey')
    op.drop_column('matchings', 'freight_id')
    op.add_column('freights', sa.Column('matching_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('freights_matching_id_fkey'), 'freights', 'matchings', ['matching_id'], ['id'])
    op.alter_column('freights', 'status',
               existing_type=sa.Enum('ACCEPTED', 'STARTING', 'DRAFT', 'PENDING', 'MATCHED', 'CONFIRMED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'EXPIRED', 'SEARCHING', 'FAILED', 'DRIVERS_FOUND', 'OFFERS_SENT', name='freightstatus'),
               type_=postgresql.ENUM('DRAFT', 'PENDING', 'MATCHED', 'MATCHING', 'CONFIRMED', 'IN_PROGRESS', 'COMPLETED', 'CANCELED', 'EXPIRED', 'SEARCHING', 'FAILED', 'ACCEPTED', 'TIMEOUT', 'REJECTED', name='triprequeststatus'),
               existing_nullable=True)
    # ### end Alembic commands ###
