"""add has_helpers to drivers

Revision ID: 06e1063ba600
Revises: 20250626_add_scheduled_freighttype_volume_roundtrip_to_ride
Create Date: 2025-06-26 05:28:26.005210

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06e1063ba600'
down_revision: Union[str, Sequence[str], None] = '20250626_add_scheduled_freighttype_volume_roundtrip_to_ride'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drivers', sa.Column('has_helpers', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('drivers', sa.Column('helper_price', sa.Float(), nullable=True))
    op.add_column('drivers', sa.Column('is_blocked', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('vehicles', sa.Column('size', sa.String(), nullable=False, server_default='P'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'size')
    op.drop_column('drivers', 'is_blocked')
    op.drop_column('drivers', 'helper_price')
    op.drop_column('drivers', 'has_helpers')
    # ### end Alembic commands ###
