"""add license_category to vehicle

Revision ID: 0eaf8b248237
Revises: 45c5926352b1
Create Date: 2025-06-22 23:27:22.015737

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0eaf8b248237'
down_revision: Union[str, Sequence[str], None] = '45c5926352b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('license_category', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'license_category')
    # ### end Alembic commands ###
