"""recreate all tables

Revision ID: 39e533be9603
Revises: e80e0d866355
Create Date: 2025-09-28 18:23:27.280439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '39e533be9603'
down_revision: Union[str, Sequence[str], None] = 'e80e0d866355'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_tokens_blacklists_',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tokens', sa.String(length=500), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_role', sa.String(), nullable=False),
    sa.Column('blacklisted_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix__tokens_blacklists__id'), '_tokens_blacklists_', ['id'], unique=False)
    op.create_index(op.f('ix__tokens_blacklists__tokens'), '_tokens_blacklists_', ['tokens'], unique=True)
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('cpf', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('postal_code', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    op.create_index(op.f('ix_clients_email'), 'clients', ['email'], unique=True)
    op.create_index(op.f('ix_clients_id'), 'clients', ['id'], unique=False)
    op.create_index(op.f('ix_clients_name'), 'clients', ['name'], unique=False)
    op.create_table('drivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('birth_date', sa.DateTime(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('cpf', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('postal_code', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    op.create_index(op.f('ix_drivers_email'), 'drivers', ['email'], unique=True)
    op.create_index(op.f('ix_drivers_id'), 'drivers', ['id'], unique=False)
    op.create_index(op.f('ix_drivers_name'), 'drivers', ['name'], unique=False)
    op.create_table('helpers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('birth_date', sa.DateTime(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('cpf', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('postal_code', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    op.create_index(op.f('ix_helpers_email'), 'helpers', ['email'], unique=True)
    op.create_index(op.f('ix_helpers_id'), 'helpers', ['id'], unique=False)
    op.create_index(op.f('ix_helpers_name'), 'helpers', ['name'], unique=False)
    op.create_table('surge_zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone_name', sa.String(length=100), nullable=False),
    sa.Column('city', sa.String(length=50), nullable=False),
    sa.Column('center_lat', sa.Float(), nullable=False),
    sa.Column('center_lng', sa.Float(), nullable=False),
    sa.Column('radius_km', sa.Float(), nullable=True),
    sa.Column('current_multiplier', sa.Float(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('client_auth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('two_fa_secret', sa.String(), nullable=True),
    sa.Column('reset_code', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id')
    )
    op.create_index(op.f('ix_client_auth_id'), 'client_auth', ['id'], unique=False)
    op.create_table('client_meta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id')
    )
    op.create_index(op.f('ix_client_meta_id'), 'client_meta', ['id'], unique=False)
    op.create_table('driver_auth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('two_fa_secret', sa.String(), nullable=True),
    sa.Column('reset_code', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_blocked', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('driver_id')
    )
    op.create_index(op.f('ix_driver_auth_id'), 'driver_auth', ['id'], unique=False)
    op.create_table('driver_meta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('is_online', sa.Boolean(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('driver_id')
    )
    op.create_index(op.f('ix_driver_meta_id'), 'driver_meta', ['id'], unique=False)
    op.create_table('driver_offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('helper_id', sa.Integer(), nullable=False),
    sa.Column('offered_price', sa.Float(), nullable=False),
    sa.Column('estimated_pickup_time', sa.DateTime(), nullable=False),
    sa.Column('compatibility_score', sa.Float(), nullable=False),
    sa.Column('offer_expires_at', sa.DateTime(), nullable=False),
    sa.Column('response', sa.Enum('DRAFT', 'PENDING', 'MATCHED', 'MATCHING', 'CONFIRMED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'EXPIRED', 'SEARCHING', 'FAILED', 'ACCEPTED', 'TIMEOUT', 'REJECTED', 'FINISHED', 'STARTING', name='triprequeststatus'), nullable=True),
    sa.Column('response_time', sa.DateTime(), nullable=True),
    sa.Column('decline_reason', sa.String(), nullable=True),
    sa.Column('response_time_seconds', sa.Integer(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['helper_id'], ['helpers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_driver_offers_id'), 'driver_offers', ['id'], unique=False)
    op.create_table('driver_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('has_helpers', sa.Boolean(), nullable=False),
    sa.Column('helper_price', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('driver_id')
    )
    op.create_index(op.f('ix_driver_services_id'), 'driver_services', ['id'], unique=False)
    op.create_table('drivers_helpers',
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('helper_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['helper_id'], ['helpers.id'], ),
    sa.PrimaryKeyConstraint('driver_id', 'helper_id')
    )
    op.create_table('freights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('ACCEPTED', 'STARTING', 'DRAFT', 'PENDING', 'MATCHED', 'CONFIRMED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'EXPIRED', 'SEARCHING', 'FAILED', 'DRIVERS_FOUND', 'OFFERS_SENT', name='freightstatus'), nullable=True),
    sa.Column('pickup_address', sa.Text(), nullable=False),
    sa.Column('pickup_lat', sa.Float(), nullable=False),
    sa.Column('pickup_lng', sa.Float(), nullable=False),
    sa.Column('delivery_address', sa.Text(), nullable=False),
    sa.Column('delivery_lat', sa.Float(), nullable=False),
    sa.Column('delivery_lng', sa.Float(), nullable=False),
    sa.Column('freight_type', sa.String(), nullable=False),
    sa.Column('estimated_weight', sa.Float(), nullable=True),
    sa.Column('estimated_volume', sa.Float(), nullable=True),
    sa.Column('estimated_price', sa.Float(), nullable=True),
    sa.Column('final_price', sa.Float(), nullable=True),
    sa.Column('request_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('current_location', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_freights_id'), 'freights', ['id'], unique=False)
    op.create_table('helper_auth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('helper_id', sa.Integer(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('two_fa_secret', sa.String(), nullable=True),
    sa.Column('reset_code', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['helper_id'], ['helpers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('helper_id')
    )
    op.create_index(op.f('ix_helper_auth_id'), 'helper_auth', ['id'], unique=False)
    op.create_table('helper_meta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('helper_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['helper_id'], ['helpers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('helper_id')
    )
    op.create_index(op.f('ix_helper_meta_id'), 'helper_meta', ['id'], unique=False)
    op.create_table('search_helper',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('helper_id', sa.Integer(), nullable=False),
    sa.Column('is_online', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['helper_id'], ['helpers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_helper_id'), 'search_helper', ['id'], unique=False)
    op.create_table('vehicles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('brand', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('plate', sa.String(), nullable=False),
    sa.Column('license_category', sa.Enum('A', 'B', 'C', 'D', 'E', 'AB', name='license_category'), nullable=False),
    sa.Column('chassis', sa.String(), nullable=True),
    sa.Column('tracker_enabled', sa.Boolean(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'UNDER_REVIEW', name='vehicle_status'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('size', sa.Enum('SMALL', 'MEDIUM', 'LARGE', name='vehicle_size'), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chassis'),
    sa.UniqueConstraint('plate')
    )
    op.create_table('matchings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('freight_id', sa.Integer(), nullable=True),
    sa.Column('driver_offer_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PENDING', 'MATCHED', 'CONFIRMED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'EXPIRED', 'SEARCHING', 'FAILED', 'DRIVERS_FOUND', 'OFFERS_SENT', 'ACCEPTED', 'TIMEOUT', 'REJECTED', name='matchingstatus'), nullable=True),
    sa.Column('failure_reason', sa.String(), nullable=True),
    sa.Column('search_radius_km', sa.Float(), nullable=True),
    sa.Column('max_search_radius_km', sa.Float(), nullable=True),
    sa.Column('min_driver_rating', sa.Float(), nullable=True),
    sa.Column('preferred_vehicle_types', sa.Text(), nullable=True),
    sa.Column('drivers_found_count', sa.Integer(), nullable=True),
    sa.Column('offers_sent_count', sa.Integer(), nullable=True),
    sa.Column('declined_count', sa.Integer(), nullable=True),
    sa.Column('timeout_count', sa.Integer(), nullable=True),
    sa.Column('selected_driver_id', sa.Integer(), nullable=True),
    sa.Column('selected_vehicle_id', sa.Integer(), nullable=True),
    sa.Column('match_score', sa.Float(), nullable=True),
    sa.Column('matched_price', sa.Float(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('first_offer_sent_at', sa.DateTime(), nullable=True),
    sa.Column('matched_at', sa.DateTime(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('failed_at', sa.DateTime(), nullable=True),
    sa.Column('total_search_time_seconds', sa.Integer(), nullable=True),
    sa.Column('average_response_time_seconds', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['driver_offer_id'], ['driver_offers.id'], ),
    sa.ForeignKeyConstraint(['freight_id'], ['freights.id'], ),
    sa.ForeignKeyConstraint(['selected_driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['selected_vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matchings_id'), 'matchings', ['id'], unique=False)
    op.create_table('rides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('start_location', sa.String(), nullable=False),
    sa.Column('end_location', sa.String(), nullable=False),
    sa.Column('distance', sa.Float(), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('fare', sa.Float(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('scheduled', sa.Boolean(), nullable=False),
    sa.Column('freight_type', sa.String(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('round_trip', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rides_id'), 'rides', ['id'], unique=False)
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ride_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.String(), nullable=False),
    sa.Column('longitude', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ride_id'], ['rides.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locations_id'), 'locations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_locations_id'), table_name='locations')
    op.drop_table('locations')
    op.drop_index(op.f('ix_rides_id'), table_name='rides')
    op.drop_table('rides')
    op.drop_index(op.f('ix_matchings_id'), table_name='matchings')
    op.drop_table('matchings')
    op.drop_table('vehicles')
    op.drop_index(op.f('ix_search_helper_id'), table_name='search_helper')
    op.drop_table('search_helper')
    op.drop_index(op.f('ix_helper_meta_id'), table_name='helper_meta')
    op.drop_table('helper_meta')
    op.drop_index(op.f('ix_helper_auth_id'), table_name='helper_auth')
    op.drop_table('helper_auth')
    op.drop_index(op.f('ix_freights_id'), table_name='freights')
    op.drop_table('freights')
    op.drop_table('drivers_helpers')
    op.drop_index(op.f('ix_driver_services_id'), table_name='driver_services')
    op.drop_table('driver_services')
    op.drop_index(op.f('ix_driver_offers_id'), table_name='driver_offers')
    op.drop_table('driver_offers')
    op.drop_index(op.f('ix_driver_meta_id'), table_name='driver_meta')
    op.drop_table('driver_meta')
    op.drop_index(op.f('ix_driver_auth_id'), table_name='driver_auth')
    op.drop_table('driver_auth')
    op.drop_index(op.f('ix_client_meta_id'), table_name='client_meta')
    op.drop_table('client_meta')
    op.drop_index(op.f('ix_client_auth_id'), table_name='client_auth')
    op.drop_table('client_auth')
    op.drop_table('surge_zones')
    op.drop_index(op.f('ix_helpers_name'), table_name='helpers')
    op.drop_index(op.f('ix_helpers_id'), table_name='helpers')
    op.drop_index(op.f('ix_helpers_email'), table_name='helpers')
    op.drop_table('helpers')
    op.drop_index(op.f('ix_drivers_name'), table_name='drivers')
    op.drop_index(op.f('ix_drivers_id'), table_name='drivers')
    op.drop_index(op.f('ix_drivers_email'), table_name='drivers')
    op.drop_table('drivers')
    op.drop_index(op.f('ix_clients_name'), table_name='clients')
    op.drop_index(op.f('ix_clients_id'), table_name='clients')
    op.drop_index(op.f('ix_clients_email'), table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix__tokens_blacklists__tokens'), table_name='_tokens_blacklists_')
    op.drop_index(op.f('ix__tokens_blacklists__id'), table_name='_tokens_blacklists_')
    op.drop_table('_tokens_blacklists_')
    # ### end Alembic commands ###
