"""add address and extra fields to drivers

Revision ID: 45c5926352b1
Revises: 51e4bb876184
Create Date: 2025-06-22 22:34:22.423458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45c5926352b1'
down_revision: Union[str, Sequence[str], None] = '51e4bb876184'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drivers', sa.Column('address', sa.String(), nullable=True))
    op.add_column('drivers', sa.Column('postal_code', sa.String(), nullable=True))
    op.add_column('drivers', sa.Column('country', sa.String(), nullable=True))
    op.add_column('drivers', sa.Column('rating', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drivers', 'rating')
    op.drop_column('drivers', 'country')
    op.drop_column('drivers', 'postal_code')
    op.drop_column('drivers', 'address')
    # ### end Alembic commands ###
