"""add locations table

Revision ID: 686673e18d68
Revises: 06e1063ba600
Create Date: 2025-06-30 20:42:44.836660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '686673e18d68'
down_revision: Union[str, Sequence[str], None] = '06e1063ba600'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rides', 'vehicle_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rides', 'vehicle_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
