"""add locations table

Revision ID: 70065483f996
Revises: 686673e18d68
Create Date: 2025-06-30 21:18:25.900279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70065483f996'
down_revision: Union[str, Sequence[str], None] = '686673e18d68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rides', 'vehicle_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rides', 'vehicle_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
