"""create token blacklist table

Revision ID: 954e9abda56a
Revises: e8a60a1902fd
Create Date: 2025-07-21 00:45:51.484713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '954e9abda56a'
down_revision: Union[str, Sequence[str], None] = 'e8a60a1902fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vehicles', 'license_category',
               existing_type=postgresql.ENUM('A', 'B', 'C', 'D', 'E', 'AB', name='license_category'),
               nullable=False)
    op.alter_column('vehicles', 'status',
               existing_type=postgresql.ENUM('ACTIVE', 'INACTIVE', 'UNDER_REVIEW', name='vehicle_status'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vehicles', 'status',
               existing_type=postgresql.ENUM('ACTIVE', 'INACTIVE', 'UNDER_REVIEW', name='vehicle_status'),
               nullable=False)
    op.alter_column('vehicles', 'license_category',
               existing_type=postgresql.ENUM('A', 'B', 'C', 'D', 'E', 'AB', name='license_category'),
               nullable=True)
    # ### end Alembic commands ###
