"""Model Helper

Revision ID: a07896cd89ce
Revises: 42e45788f07d
Create Date: 2025-07-27 16:43:53.760647

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a07896cd89ce'
down_revision: Union[str, Sequence[str], None] = '42e45788f07d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('helpers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('birth_date', sa.DateTime(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('cpf', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('postal_code', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('two_fa_secret', sa.String(), nullable=True),
    sa.Column('reset_code', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf')
    )
    op.create_index(op.f('ix_helpers_email'), 'helpers', ['email'], unique=True)
    op.create_index(op.f('ix_helpers_id'), 'helpers', ['id'], unique=False)
    op.create_index(op.f('ix_helpers_name'), 'helpers', ['name'], unique=False)
    op.create_table('drivers_helpers',
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('helper_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ),
    sa.ForeignKeyConstraint(['helper_id'], ['helpers.id'], ),
    sa.PrimaryKeyConstraint('driver_id', 'helper_id')
    )
    op.drop_index(op.f('ix_token_blacklist_id'), table_name='token_blacklist')
    op.drop_index(op.f('ix_token_blacklist_token'), table_name='token_blacklist')
    op.drop_table('token_blacklist')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_blacklist',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('token', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_role', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('blacklisted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('token_blacklist_pkey'))
    )
    op.create_index(op.f('ix_token_blacklist_token'), 'token_blacklist', ['token'], unique=True)
    op.create_index(op.f('ix_token_blacklist_id'), 'token_blacklist', ['id'], unique=False)
    op.drop_table('drivers_helpers')
    op.drop_index(op.f('ix_helpers_name'), table_name='helpers')
    op.drop_index(op.f('ix_helpers_id'), table_name='helpers')
    op.drop_index(op.f('ix_helpers_email'), table_name='helpers')
    op.drop_table('helpers')
    # ### end Alembic commands ###
