"""Permite driver_id e vehicle_id serem nulos em rides

Revision ID: df09ff112e3e
Revises: 0eaf8b248237
Create Date: 2025-06-23 03:50:50.321065

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df09ff112e3e'
down_revision: Union[str, Sequence[str], None] = '0eaf8b248237'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rides', 'driver_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('rides', 'vehicle_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('rides', 'vehicle_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('rides', 'driver_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
