"""add pending to freightstatus

Revision ID: e80e0d866355
Revises: d739081a1378
Create Date: 2025-09-28 17:47:47.117404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e80e0d866355'
down_revision: Union[str, Sequence[str], None] = 'd739081a1378'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('freights', 'status',
               existing_type=postgresql.ENUM('ACCEPTED', 'STARTING', 'DRAFT', 'PENDING', 'MATCHED', 'CONFIRMED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'EXPIRED', 'SEARCHING', 'FAILED', 'DRIVERS_FOUND', 'OFFERS_SENT', name='freightstatus'),
               type_=sa.Enum('ACCEPTED', 'STARTING', 'DRAFT', 'PENDING', 'MATCHED', 'CONFIRMED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'EXPIRED', 'SEARCHING', 'FAILED', 'DRIVERS_FOUND', 'OFFERS_SENT', name='freight-status'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('freights', 'status',
               existing_type=sa.Enum('ACCEPTED', 'STARTING', 'DRAFT', 'PENDING', 'MATCHED', 'CONFIRMED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'EXPIRED', 'SEARCHING', 'FAILED', 'DRIVERS_FOUND', 'OFFERS_SENT', name='freight-status'),
               type_=postgresql.ENUM('ACCEPTED', 'STARTING', 'DRAFT', 'PENDING', 'MATCHED', 'CONFIRMED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'EXPIRED', 'SEARCHING', 'FAILED', 'DRIVERS_FOUND', 'OFFERS_SENT', name='freightstatus'),
               existing_nullable=True)
    # ### end Alembic commands ###
